package cool.parser;

import java.util.ArrayList;
import beaver.*;
import cool.parser.ast.*;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "cool.grammar".
 */
public class SimpleParser extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pLc6Tu5KKKXh$T2maYaII4W4WWb0X6lA4RGa9leWXsQVQkA5Qme6815RjYGy66sCMAs4L" +
		"4B8YYWg3O5HMnzpQ#EtSIzoutcyV7FxhtUUVCVEVCsTdPsTr997#P3j9#wgyZTPYErG7QKa" +
		"VhS1sX2SQebJfheavMcKxH2TfMszKQ#xkDVT3ygKDhYz4cDcOBZNJv3ZH$g4GzjBakgpNlS" +
		"jkdjemDOhtPiTu#iTvHiTxROhsDOhsRndgRn7eBOhrJOxt$TpsqRdIwNJUdfMcRMMsmUInD" +
		"tTggRTqgxgsXQTu7hBTzcdQ$rP9fsXrMwvwsTX#rsevfsdAh7Pn1koGjtsvMkuvH$QrbgmW" +
		"jh3oaueWoHrsjKlr4dgeiyi#fKNgfddpDL5FK6KwTh2pbAmyrJmdDCFSGKr#5HEIhiN8Wby" +
		"Wg8iVh6hWI1ca0Z85zy1s5RwAEiUL9bESHSPDkrUtgHCJrkaUJoBQDUcgApbMbJjGuxQw6Q" +
		"7lf3BD6ksWSzN6Qf3EvycOQYxQlpg8#LnKsFk1EDLSBjTOyjTHTQgCEwgXsAjLMwa9KDvMh" +
		"ByzigVffe8Pec8PhX7RM3jfUEvcL6grTjOTvNNjhJxF2l4RS$d2yfkaGUXv7p#0tJNtC0pf" +
		"RqtMEpkTvkK1Nw2By5#fYNQgRTRckrYpph6RhAbsh6yXmesunpvX5Ph7kvZhdwrxTfmLwGW" +
		"lrg1xNKtfIY$I85kjXFQPdjKHBzPoUrwkIdjOBMgrdz99Ur38jrogzfTUrnhoiD$MsWcE5N" +
		"jPhs5UKEbOg$NX37dSpOUzN5kkZ0M$GXhm$6k7RZFlMaRafPOLtOkuBwuXDOlDhZQdQA9#u" +
		"pvsP#HPrvAtDcnlhRHNhBOZrjelrUh7UHAotRwntyrYl$oz6zN$Nm#icwTPDMCjnMawQEZ0" +
		"IsR$EFEKPj04nvykqdkkAQvP1QsMriD9X8oMnaP8aVoAaz6J$LCWNA8ULLAqcUTybKPCQZ3" +
		"hKnZIXLslUv1MML6GIDQccq8slK3KfNxXCyciB#Vo2Y4BkLdD#9Nn7A$a2jSJdynxCuHuEe" +
		"knXHvaaAfyhpwNT39hRUXiR7v3FcVEu#osmpMaLaACzxQxGXdOHxGBRpY4kZrPJhY6NCVUZ" +
		"LOpQ18fHSlYb#dKbAkYPIyy2cx60g4h8fUunJpwr8jh1kOVOlBbapREZ2BBaaIDXV#LSfsz" +
		"xjWg#RCna5bUGpJFNcgUkBJqQ49$WV3cgnwws7R715GHNayTvDs4Lbx2MHOP6XeEhBbPBR1" +
		"jZ3nMPj8FPbDQURb$ItboAu6tO5dQ4m5S58#0g$3zZvxhO5R2xgw#5CN0XZRiW#19yI7kTv" +
		"7U0CjhziTrJyNutYb6kFfXYRsmvzaZiLjWfWS$vjuNXC2BLvbidVrDNdnMA6qbnExOVTg4R" +
		"bw7u1Aqdzbji4VPFBDVeCKT#CAQTORTGdkq3QsT6$Z2dRUViQDW1c1j$AC9Ix2ZimTWnxfm" +
		"tKdVpudU4dM0F6E2qrh0dZ0NcsH$Yz18O1uU6nh8BHLFi#6ej2kShnB#NgmVvWhdS5mvtEJ" +
		"gZyyNqssChiFl0Vi2zzOPWzm#TxmXe1mV0iKux20vBFwT$8fmCmVqw2YOW1lVv6ES$pjbJE" +
		"4SmxnFXUATDWXEehC9E3kKy3QQuEkyu$sm8xlK5mBhoBuA6pj$5sLETlGpEXEaRpuz$4b3r" +
		"puAfS0QS2rV0vN0bJ8Dpu18u3ow5Q#5cc0atmIou6dWE$6lWUhWEPiCSuDdnRu3W$byCjy0" +
		"y2DRahN07t0ct0S#8ly3Ti$cXUxaeF7QMu4ze6wXETlx5eTWb6TR2tUbjDOxuPuRgivtjv#" +
		"p837DNv7nRX$gDZkISvspDEcBSwvnM$HmETtPrA7U9qrQ6SlM8ZY73DKu8vIXsscynyMyIb" +
		"yYWhq6lx$BqYlWcrJ66TQ7wvw7nz0xfYvtT4EaxFz8Ezw#CFs$g7HBgEpKkFiEuPuJgwoEv" +
		"#pWxFj9dP2Hkx3yvvtyDZhMA7Fmz5vJBRFburEjY7Z4VKFwMflrYVdMrLuCSvcbuqhnIu$y" +
		"vU7xD3y0xq7mD6wp#det#7Duoh4wpEYthUlZHrjv87o5sLSretp5hpTlcErl$pAmpdvfFpC" +
		"Vc8reVsf6#Rptlccyelu8lp7hp9VPxyvHveYRVVRQSR#utzqQkTo4yNDDQK5Dxo9t$mKZyI" +
		"$0YB7Nj9UPvyvnv8VDi$ejZ53jBZvsb3vwjTs4tr0LRnYwfZ3rJcQqdsC5MuzazxJROJjWK" +
		"7ZlMXCDZlvbm17NVMI$I3cmz6rTAkvHsOBjZksExeQVmsEjaiLzCiF$CXlhWiQkj1vxzwtK" +
		"mNykUw5NqhIAk2ds09M5jER5zxExMOx$eWsTtY0En0vtjYwt0Lq6z5$k#NkmCKzI7RFl$az" +
		"x43C8$oDbAxB2$0E7D#$y=");

	public SimpleParser() {
		super(PARSING_TABLES);
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		switch(rule_num) {
			case 0: // program = class_list.cl
			{
					final Symbol _symbol_cl = _symbols[offset + 1];
					final ArrayList cl = (ArrayList) _symbol_cl.value;
					 return new Symbol(cl);
			}
			case 1: // class_list = classdecl.cd class_list.cl
			{
					final Symbol cd = _symbols[offset + 1];
					final Symbol _symbol_cl = _symbols[offset + 2];
					final ArrayList cl = (ArrayList) _symbol_cl.value;
					 cl.add(cd); return new Symbol(cl);
			}
			case 2: // class_list = empty
			{
					 return new Symbol( new ArrayList() );
			}
			case 4: // expr = lexpr.le ASSIGN rexpr.re
			{
					final Symbol le = _symbols[offset + 1];
					final Symbol _symbol_re = _symbols[offset + 3];
					final Expr re = (Expr) _symbol_re.value;
					 ArrayList operands = new ArrayList(); operands.add(le); operands.add(re); return new AssignmentOperation(operands);
			}
			case 5: // expr = rexpr.r
			{
					final Symbol _symbol_r = _symbols[offset + 1];
					final Expr r = (Expr) _symbol_r.value;
					 return r;
			}
			case 6: // rexpr = IF LPAREN rexpr.cond RPAREN expr.m ELSE expr.e
			{
					final Symbol _symbol_cond = _symbols[offset + 3];
					final Expr cond = (Expr) _symbol_cond.value;
					final Symbol _symbol_m = _symbols[offset + 5];
					final Expr m = (Expr) _symbol_m.value;
					final Symbol _symbol_e = _symbols[offset + 7];
					final Expr e = (Expr) _symbol_e.value;
					 return new IfNode( cond, m, e);
			}
			case 7: // rexpr = WHILE LPAREN rexpr.cond RPAREN expr.e
			{
					final Symbol _symbol_cond = _symbols[offset + 3];
					final Expr cond = (Expr) _symbol_cond.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expr e = (Expr) _symbol_e.value;
					 return new WhileNode( cond, e);
			}
			case 8: // rexpr = rel.r
			{
					final Symbol r = _symbols[offset + 1];
					 return r;
			}
			case 9: // rexpr = primary.p MATCH cases.c
			{
					final Symbol p = _symbols[offset + 1];
					final Symbol _symbol_c = _symbols[offset + 3];
					final ArrayList c = (ArrayList) _symbol_c.value;
					 Expr e = (Expr) p.value; return new Match(e, c);
			}
			case 10: // rel = rel.r LE equiv.e
			{
					final Symbol r = _symbols[offset + 1];
					final Symbol e = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(r); operands.add(e); return new LessOrEqual(operands);
			}
			case 11: // rel = rel.r LT equiv.e
			{
					final Symbol r = _symbols[offset + 1];
					final Symbol e = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(r); operands.add(e); return new LessThan(operands);
			}
			case 12: // rel = equiv.e
			{
					final Symbol e = _symbols[offset + 1];
					 return e;
			}
			case 13: // equiv = equiv.e EQUALS sum.s
			{
					final Symbol e = _symbols[offset + 1];
					final Symbol s = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(e); operands.add(s); return new Equal(operands);
			}
			case 14: // equiv = sum.s
			{
					final Symbol s = _symbols[offset + 1];
					 return s;
			}
			case 15: // sum = sum.s PLUS product.p
			{
					final Symbol s = _symbols[offset + 1];
					final Symbol p = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(s); operands.add(p); return new PlusOperation(operands);
			}
			case 16: // sum = sum.s MINUS product.p
			{
					final Symbol s = _symbols[offset + 1];
					final Symbol p = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(s); operands.add(p); return new MinusOperation(operands);
			}
			case 17: // sum = product.p
			{
					final Symbol p = _symbols[offset + 1];
					 return p;
			}
			case 18: // product = product.p TIMES primary.i
			{
					final Symbol p = _symbols[offset + 1];
					final Symbol i = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(p); operands.add(i); return new MultiplyOperation(operands);
			}
			case 19: // product = product.p DIV primary.i
			{
					final Symbol p = _symbols[offset + 1];
					final Symbol i = _symbols[offset + 3];
					 ArrayList operands = new ArrayList(); operands.add(p); operands.add(i); return new DivisionOperation(operands);
			}
			case 20: // product = primary.p
			{
					final Symbol p = _symbols[offset + 1];
					 return p;
			}
			case 21: // primary = LBRACE block.b RBRACE
			{
					final Symbol _symbol_b = _symbols[offset + 2];
					final Block b = (Block) _symbol_b.value;
					 return (Expr)b;
			}
			case 22: // primary = LPAREN expr.e RPAREN
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return e;
			}
			case 23: // primary = NULL
			{
					 return new NullNode();
			}
			case 24: // primary = LPAREN RPAREN
			{
					 return new Unit();
			}
			case 25: // primary = INTEGER.i
			{
					final Symbol _symbol_i = _symbols[offset + 1];
					final String i = (String) _symbol_i.value;
					 return new IntegerNode(Integer.parseInt(i));
			}
			case 26: // primary = STRING.s
			{
					final Symbol _symbol_s = _symbols[offset + 1];
					final String s = (String) _symbol_s.value;
					 return new StringNode(s);
			}
			case 27: // primary = BOOLEAN.b
			{
					final Symbol _symbol_b = _symbols[offset + 1];
					final Boolean b = (Boolean) _symbol_b.value;
					 return new BooleanNode(b);
			}
			case 28: // primary = MINUS primary.p
			{
					final Symbol p = _symbols[offset + 2];
					 ArrayList operands = new ArrayList() ; operands.add(p); return new UnaryMinusOperation(operands);
			}
			case 29: // primary = lexpr.e
			{
					final Symbol e = _symbols[offset + 1];
					 return e;
			}
			case 30: // primary = NOT primary.p
			{
					final Symbol p = _symbols[offset + 2];
					 ArrayList operands = new ArrayList() ; operands.add(p); return new UnaryNotOperation(operands);
			}
			case 31: // primary = primary.p DOT ID.id actuals.a
			{
					final Symbol p = _symbols[offset + 1];
					final Symbol _symbol_id = _symbols[offset + 3];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_a = _symbols[offset + 4];
					final ArrayList a = (ArrayList) _symbol_a.value;
					 Primary pp = (Primary)p.value ; return new PrimaryActual(a,pp, id);
			}
			case 32: // primary = NEW TYPE.t actuals.s
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_s = _symbols[offset + 3];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Instance(t,s);
			}
			case 33: // ident = ID.id
			{
					final Symbol _symbol_id = _symbols[offset + 1];
					final String id = (String) _symbol_id.value;
					 return new Id(id);
			}
			case 34: // ident = ID.id actuals.s
			{
					final Symbol _symbol_id = _symbols[offset + 1];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_s = _symbols[offset + 2];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Method(id,s);
			}
			case 35: // ident = THIS
			{
					 return new Id("this");
			}
			case 36: // block = st_list.el expr.e
			{
					final Symbol el = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 ArrayList es = (ArrayList) el.value; return new Block(es , e);
			}
			case 37: // block = empty
			{
					 return new Block();
			}
			case 38: // st_list = st_list.el new_var.ve SEMI
			{
					final Symbol el = _symbols[offset + 1];
					final Symbol ve = _symbols[offset + 2];
					 ArrayList es = (ArrayList) el.value; es.add(ve); return new Symbol(es);
			}
			case 39: // st_list = st_list.el expr.e SEMI
			{
					final Symbol el = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 ArrayList es = (ArrayList) el.value; es.add(e); return new Symbol(es);
			}
			case 40: // st_list = empty
			{
					 ArrayList el = new ArrayList(); return new Symbol(el);
			}
			case 41: // new_var = VAR ID.id COLON TYPE.t ASSIGN expr.e
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_e = _symbols[offset + 6];
					final Expr e = (Expr) _symbol_e.value;
					 return new VarExpr( id, t, e);
			}
			case 42: // cases = LBRACE case_block.cb RBRACE
			{
					final Symbol _symbol_cb = _symbols[offset + 2];
					final ArrayList cb = (ArrayList) _symbol_cb.value;
					 return new Symbol(cb);
			}
			case 43: // case_block = CASE ID.id COLON TYPE.t ARROW block.b case_block.cb
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_b = _symbols[offset + 6];
					final Block b = (Block) _symbol_b.value;
					final Symbol _symbol_cb = _symbols[offset + 7];
					final ArrayList cb = (ArrayList) _symbol_cb.value;
					 cb.add(new Case(id,t,b));return new Symbol(cb);
			}
			case 44: // case_block = CASE NULL ARROW block.b case_block.cb
			{
					final Symbol _symbol_b = _symbols[offset + 4];
					final Block b = (Block) _symbol_b.value;
					final Symbol _symbol_cb = _symbols[offset + 5];
					final ArrayList cb = (ArrayList) _symbol_cb.value;
					 cb.add(new Case(b));return new Symbol(cb);
			}
			case 45: // case_block = empty
			{
					 return new Symbol(new ArrayList());
			}
			case 46: // lexpr = SUPER DOT ID.id actuals.a
			{
					final Symbol _symbol_id = _symbols[offset + 3];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_a = _symbols[offset + 4];
					final ArrayList a = (ArrayList) _symbol_a.value;
					 return new SuperActual(id,a);
			}
			case 47: // lexpr = ident.id
			{
					final Symbol _symbol_id = _symbols[offset + 1];
					final Id id = (Id) _symbol_id.value;
					 return id;
			}
			case 50: // classdecl = CLASS TYPE.t varformals.v have_extends.e classbody.fl
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_v = _symbols[offset + 3];
					final ArrayList v = (ArrayList) _symbol_v.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Extends e = (Extends) _symbol_e.value;
					final Symbol fl = _symbols[offset + 5];
					 return new ClassNode(t, v, e, (ArrayList)fl.value);
			}
			case 51: // varformals = LPAREN RPAREN
			{
					 return new Symbol(new ArrayList());
			}
			case 52: // varformals = LPAREN var_list.vl RPAREN
			{
					final Symbol _symbol_vl = _symbols[offset + 2];
					final ArrayList vl = (ArrayList) _symbol_vl.value;
					 return new Symbol(vl);
			}
			case 53: // varformals = empty
			{
					 return new Symbol(new ArrayList());
			}
			case 54: // var_list = one_var.v
			{
					final Symbol _symbol_v = _symbols[offset + 1];
					final Var v = (Var) _symbol_v.value;
					 ArrayList vl = new ArrayList(); vl.add(v); return new Symbol(vl);
			}
			case 55: // var_list = var_list.vl COMMA one_var.v
			{
					final Symbol _symbol_vl = _symbols[offset + 1];
					final ArrayList vl = (ArrayList) _symbol_vl.value;
					final Symbol _symbol_v = _symbols[offset + 3];
					final Var v = (Var) _symbol_v.value;
					 vl.add(v); return new Symbol(vl);
			}
			case 56: // var_list = empty
			{
					 new Symbol( new ArrayList() );
			}
			case 57: // one_var = VAR ID.id COLON TYPE.t
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final String t = (String) _symbol_t.value;
					 return new Var(id, t);
			}
			case 58: // have_extends = EXTENDS type_or_native.ext
			{
					final Symbol ext = _symbols[offset + 2];
					 return ext;
			}
			case 60: // type_or_native = TYPE.t actuals.a
			{
					final Symbol _symbol_t = _symbols[offset + 1];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_a = _symbols[offset + 2];
					final ArrayList a = (ArrayList) _symbol_a.value;
					 return new Extends(t, a);
			}
			case 61: // type_or_native = NATIVE
			{
					 return new Extends();
			}
			case 62: // actuals = LPAREN exp_list.el RPAREN
			{
					final Symbol _symbol_el = _symbols[offset + 2];
					final ArrayList el = (ArrayList) _symbol_el.value;
					 return new Symbol(el);
			}
			case 63: // exp_list = expr.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					 ArrayList el = new ArrayList(); el.add(e); return new Symbol(el);
			}
			case 64: // exp_list = exp_list.el COMMA expr.e
			{
					final Symbol _symbol_el = _symbols[offset + 1];
					final ArrayList el = (ArrayList) _symbol_el.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 el.add(e); return new Symbol(el);
			}
			case 65: // exp_list = empty
			{
					 return new Symbol( new ArrayList() );
			}
			case 66: // classbody = LBRACE feature_list.fl RBRACE
			{
					final Symbol _symbol_fl = _symbols[offset + 2];
					final ArrayList fl = (ArrayList) _symbol_fl.value;
					 return new Symbol(fl);
			}
			case 67: // feature_list = feature.f feature_list.fl
			{
					final Symbol _symbol_f = _symbols[offset + 1];
					final Feature f = (Feature) _symbol_f.value;
					final Symbol _symbol_fl = _symbols[offset + 2];
					final ArrayList fl = (ArrayList) _symbol_fl.value;
					 fl.add(f); return new Symbol(fl);
			}
			case 68: // feature_list = empty
			{
					 return new Symbol( new ArrayList() );
			}
			case 69: // feature = OVERRIDE DEF ID.id formals.fl COLON TYPE.t ASSIGN expr.e SEMI
			{
					final Symbol _symbol_id = _symbols[offset + 3];
					final String id = (String) _symbol_id.value;
					final Symbol fl = _symbols[offset + 4];
					final Symbol _symbol_t = _symbols[offset + 6];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_e = _symbols[offset + 8];
					final Expr e = (Expr) _symbol_e.value;
					 return new OverrideFeatureMethod(id, (ArrayList)fl.value, t, (Expr)e);
			}
			case 70: // feature = DEF ID.id formals.fl COLON TYPE.t ASSIGN expr.e SEMI
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol fl = _symbols[offset + 3];
					final Symbol _symbol_t = _symbols[offset + 5];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_e = _symbols[offset + 7];
					final Expr e = (Expr) _symbol_e.value;
					 return new FeatureMethod(id, (ArrayList)fl.value, t, (Expr)e);
			}
			case 71: // feature = DEF ID.id formals.fl COLON TYPE.t ASSIGN NATIVE SEMI
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol fl = _symbols[offset + 3];
					final Symbol _symbol_t = _symbols[offset + 5];
					final String t = (String) _symbol_t.value;
					 return new NativeFeatureMethod(id, (ArrayList)fl.value, t);
			}
			case 72: // feature = VAR ID.id ASSIGN NATIVE SEMI
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					 return new FeatureVar(id );
			}
			case 73: // feature = VAR ID.id COLON TYPE.t ASSIGN expr.e SEMI
			{
					final Symbol _symbol_id = _symbols[offset + 2];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final String t = (String) _symbol_t.value;
					final Symbol _symbol_e = _symbols[offset + 6];
					final Expr e = (Expr) _symbol_e.value;
					 return new FeatureVar(id, t, e );
			}
			case 74: // feature = LBRACE block.b RBRACE SEMI
			{
					final Symbol _symbol_b = _symbols[offset + 2];
					final Block b = (Block) _symbol_b.value;
					 return new FeatureBlock(b);
			}
			case 75: // formals = LPAREN formal_list.fl RPAREN
			{
					final Symbol _symbol_fl = _symbols[offset + 2];
					final ArrayList fl = (ArrayList) _symbol_fl.value;
					 return new Symbol(fl);
			}
			case 76: // formal_list = formal.f
			{
					final Symbol _symbol_f = _symbols[offset + 1];
					final Formal f = (Formal) _symbol_f.value;
					 ArrayList fl = new ArrayList(); fl.add(f); return new Symbol(fl);
			}
			case 77: // formal_list = formal_list.fl COMMA formal.f
			{
					final Symbol _symbol_fl = _symbols[offset + 1];
					final ArrayList fl = (ArrayList) _symbol_fl.value;
					final Symbol _symbol_f = _symbols[offset + 3];
					final Formal f = (Formal) _symbol_f.value;
					 fl.add(f); return new Symbol(fl);
			}
			case 78: // formal_list = empty
			{
					 return new Symbol( new ArrayList() );
			}
			case 79: // formal = ID.id COLON TYPE.t
			{
					final Symbol _symbol_id = _symbols[offset + 1];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final String t = (String) _symbol_t.value;
					 return new Formal(id,t);
			}
			case 48: // empty = 
			{
				return new Symbol(null);
			}
			case 3: // program = bogus
			case 59: // have_extends = empty
			{
				return _symbols[offset + 1];
			}
			case 49: // bogus = STUB CLASS EXTENDS VAR OVERRIDE DEF NATIVE NEW NULL THIS CASE MATCH IF ELSE WHILE SUPER LPAREN RPAREN LBRACE RBRACE COLON COMMA ASSIGN SEMI ARROW DOT PLUS MINUS TIMES DIV LE LT EQUALS NOT TYPE ID INTEGER STRING BOOLEAN
			{
				return _symbols[offset + 39];
			}
			default:
				throw new IllegalArgumentException("unknown production #" + rule_num);
		}
	}
}
